// Code generated by goctl. DO NOT EDIT.
package types

import(
	"mime/multipart"
)
type FileUploadRequest struct {
	File   *multipart.FileHeader `form:"file,optional"`
}

type FileUploadReply struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
type FileDeleteRequest struct {
	ID int    `json:"id"`
}

type FileDeleteReply struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type FileListRequest struct {
	Page     int    `form:"page"`         // 页码
	PageSize int    `form:"pageSize"` // 每页大小
	Keyword  string `form:"keyword,optional"`   //关键字
}

type FileListReply struct {
	List     interface{} `json:"list"`
	Total    int64       `json:"total"`
	Page     int         `json:"page"`
	PageSize int         `json:"pageSize"`
}
