// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package userclient

import (
	"context"

	"go-filedrop/service/user/rpc/types/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FileIsUserReply = user.FileIsUserReply
	FileIsUserReq   = user.FileIsUserReq

	User interface {
		FileIsUser(ctx context.Context, in *FileIsUserReq, opts ...grpc.CallOption) (*FileIsUserReply, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) FileIsUser(ctx context.Context, in *FileIsUserReq, opts ...grpc.CallOption) (*FileIsUserReply, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.FileIsUser(ctx, in, opts...)
}
