// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go-filedrop/service/store/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/store/upload",
					Handler: FileUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/store/delete",
					Handler: FileDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/store/list",
					Handler: FileListHandler(serverCtx),
				},
			}...,
		),
	)
}
